### ISSUE TITLE
[iOS] 이번주 해야할 Todo list

### ISSUE THREAD

**Issue by SHcommit** [softeerbootcamp-2nd/H1-MyCarDeepDive#14]
## 📌 할 일
- [x]  Cooperation Rule 정하기
- [x]  general component에서 추가적으로 common view로 정의할 수 있는 UI 컴포넌트 찾기
- [x]  앱 기획 피그마로 전반적으로 이해하기 + 전체적인 기능 파해치기
- [x] UI기능 명세 작성하기, 앱 흐름 파악하기
- [x]  Github convention 정하기
- [x]  Directory structure 정하기
- [x]  Github PR, issue 템플릿 정하기
- [x]  iOS Minimum target 정하기. 15.0
- [x]  xcode version 정하기. 14.3.1 ( 업데이트 노노 ) 
- [ ]  coordinator도입? 페이지 적지만.. SOLID를 따져본다면 해야할 것 같기도 합니닷,,
- [x] 자주 사용했던 porotocol, utils 코드 소개
